apiVersion: v1
kind: Service
metadata:
  labels:
    app: ldap
  name: ldap-service
  namespace: krb5ldap
spec:
  ports:
    - port: 389
      name: ldap
      targetPort: 389
      nodePort: 30389
  type: NodePort
  selector:
    app: ldap
---
apiVersion: apps/v1beta1
kind: StatefulSet
metadata:
  labels:
    app: ldap
  name: ldap
  namespace: krb5ldap
spec:
  serviceName: ldap-service
  replicas: 1
  template:
    metadata:
      labels:
        app: ldap
    spec:
      containers:
      - name: ldap
        image: osixia/openldap:1.1.9
        volumeMounts:
        - name: ldap-data
          mountPath: /var/lib/ldap
        - name: ldap-config
          mountPath: /etc/ldap/slapd.d
        - name: ldap-certs
          mountPath: /container/service/slapd/assets/certs
        ports:
        - containerPort: 389
          name: openldap
        envFrom:
        - configMapRef:
            name: ldap-conf
  volumeClaimTemplates:
  - metadata:
      name: ldap-data
    spec:
      accessModes:
        - "ReadWriteOnce"
      resources:
        requests:
          storage: 1Gi
      storageClassName: nakano-nfs-ldap-data
  - metadata:
      name: ldap-config
    spec:
      accessModes:
        - "ReadWriteOnce"
      resources:
        requests:
          storage: 1Gi
      storageClassName: nakano-nfs-ldap-config
  - metadata:
      name: ldap-certs
    spec:
      accessModes:
        - "ReadWriteOnce"
      resources:
        requests:
          storage: 1Gi
      storageClassName: nakano-nfs-ldap-certs
